# Generated by Django 3.1.7 on 2021-03-03 16:13

import AGRApi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=AGRApi.models.generate_unique_code, max_length=8, unique=True)),
                ('fullname', models.CharField(default='Noname', max_length=50)),
                ('DOB', models.CharField(default='010190', max_length=6)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'USER_CREDENTIAL_DATABASE',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_level', models.IntegerField(default=1)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('goal', models.CharField(default='', max_length=50)),
                ('accomplishment', models.CharField(default='', max_length=50)),
                ('bmi', models.IntegerField(default=0)),
                ('intensity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGRApi.user')),
            ],
            options={
                'db_table': 'USER_DATABASE',
            },
        ),
    ]
