# Generated by Django 3.1.7 on 2021-02-28 14:48

import AGRApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=AGRApi.models.generate_unique_code, max_length=8, unique=True)),
                ('sessionKey', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('trainingLevel', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
