# Generated by Django 3.1.7 on 2021-04-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bmi',
            field=models.FloatField(default=20),
        ),
    ]
