# Generated by Django 3.1.7 on 2021-04-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routineexercises',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='routineexercises',
            old_name='set_id',
            new_name='routine',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='set_id',
        ),
        migrations.AddField(
            model_name='routine',
            name='mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
