# Generated by Django 3.1.7 on 2021-03-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bmi',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fitness_level',
            field=models.IntegerField(default=0),
        ),
    ]
