# Generated by Django 3.1.7 on 2021-03-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0002_exercise_routine_routineexercises_userexerciserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(default='01011994', max_length=8),
        ),
    ]
