# Generated by Django 3.1.7 on 2021-02-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0002_auto_20210228_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sessionKey',
            new_name='session_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trainingLevel',
        ),
        migrations.AlterModelTable(
            name='user',
            table='USER_CREDENTIAL_DATABASE',
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_level', models.IntegerField(default=1)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('goal', models.CharField(default=None, max_length=50)),
                ('accomplishment', models.CharField(default=None, max_length=50)),
                ('bmi', models.IntegerField(default=0)),
                ('intensity', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGRApi.user')),
            ],
            options={
                'db_table': 'USER_DATABASE',
            },
        ),
    ]
