# Generated by Django 3.1.7 on 2021-03-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0002_auto_20210321_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routineexercises',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='routineexercises',
            old_name='set_id',
            new_name='routine',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='set_id',
        ),
    ]
