# Generated by Django 2.2.5 on 2021-03-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0003_auto_20210307_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineexercises',
            name='Exercise',
        ),
        migrations.AddField(
            model_name='routineexercises',
            name='exercise_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AGRApi.Exercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(default='010190', max_length=6),
        ),
    ]
