# Generated by Django 3.1.7 on 2021-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0003_auto_20210307_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routineexercises',
            old_name='Exercise',
            new_name='exercise_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(default='010190', max_length=6),
        ),
    ]
