# Generated by Django 3.1.7 on 2021-03-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0003_auto_20210323_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexerciserating',
            old_name='userdata',
            new_name='user',
        ),
    ]
