# Generated by Django 3.1.7 on 2021-03-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0004_auto_20210323_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
