# Generated by Django 3.1.7 on 2021-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0004_auto_20210308_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(default='010190', max_length=8),
        ),
    ]
