# Generated by Django 3.1.7 on 2021-03-09 14:54

import AGRApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0005_auto_20210309_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=AGRApi.models.generate_unique_code, max_length=6, unique=True),
        ),
    ]
