# Generated by Django 3.1.7 on 2021-03-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0007_auto_20210310_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
