# Generated by Django 3.1.7 on 2021-02-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0007_auto_20210228_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='accomplishment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='goal',
            field=models.CharField(default='', max_length=50),
        ),
    ]
