# Generated by Django 3.1.7 on 2021-02-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0008_auto_20210228_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.CharField(default='010190', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Noname', max_length=50),
        ),
    ]
