# Generated by Django 3.1.7 on 2021-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0009_remove_userdata_accomplishment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user',
            new_name='uuser',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
