# Generated by Django 3.1.7 on 2021-03-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0011_auto_20210314_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexerciserating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGRApi.userdata'),
        ),
    ]
