# Generated by Django 3.1.7 on 2021-03-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AGRApi', '0012_auto_20210314_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexerciserating',
            old_name='user_id',
            new_name='user',
        ),
    ]
